# Generated by Django 6.0.7 on 2026-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_settlementpayment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementpayment',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('card', 'Bank card')], max_length=10),
        ),
    ]
