# Generated by Django 6.0.7 on 2026-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_settlementpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementpayment',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='settlementpayment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='settlementpayment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='settlementpayment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settlementpayment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending approval'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=10),
        ),
    ]
