# Generated by Django 6.0.7 on 2026-08-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_destination_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
    ]
