# Generated by Django 6.0.7 on 2026-09-14 08:02

import secrets
import string
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def generate_join_code():
    alphabet = string.ascii_uppercase + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(8))


def populate_join_codes(apps, schema_editor):
    Tour = apps.get_model("tour", "Tour")
    used_codes = set()
    for tour in Tour.objects.filter(join_code__isnull=True).iterator():
        join_code = generate_join_code()
        while join_code in used_codes:
            join_code = generate_join_code()
        used_codes.add(join_code)
        Tour.objects.filter(pk=tour.pk).update(join_code=join_code)


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_image_alter_tour_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='join_code',
            field=models.CharField(editable=False, max_length=8, null=True),
        ),
        migrations.RunPython(
            code=populate_join_codes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='tour',
            name='join_code',
            field=models.CharField(default=generate_join_code, editable=False, max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='TourMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tour.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('tour', 'user'), name='unique_tour_member')],
            },
        ),
    ]
