# Generated by Django 6.0.7 on 2026-09-14 08:05

import apps.tour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_join_code_tourmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='join_code',
            field=models.CharField(default=apps.tour.models.generate_join_code, editable=False, max_length=8, unique=True),
        ),
    ]
